PATCH http://localhost:3000/subscriptions/644b7485c49afb81a93ea233
Content-Type: application/json

{
  "price": 8900,
  "firstPaymentDate": "2023-05-13"
}

###

DELETE http://localhost:3000/subscriptions/644b7485c49afb81a93ea231
